# -*- coding: utf-8 -*-
"""emission_pp_model_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C4tXF0l4trUrCKAiGzxO8VTrqDb7VKVI
"""

# Commented out IPython magic to ensure Python compatibility.
# MODELO
# DISCO CENTRAL + ANILLOS + PLANETAS + ASIMETRÍAS AZIMUTALES

import numpy as np
import matplotlib.pyplot as plt
import math


# if you run in colab:
#from google.colab import drive
#drive.mount('/content/drive/')
# Ajusta la ruta si tu carpeta está dentro de otras carpetas
# Por ejemplo: '/content/drive/MyDrive/proyectos/emision'
ruta_carpeta = '/content/drive/MyDrive/emission_disk'

import os
if os.path.exists(ruta_carpeta):
#     %cd {ruta_carpeta}
    print(f"Ahora estás trabajando en: {os.getcwd()}")
else:
    print("La carpeta no existe. Verifica el nombre o la ruta en tu Drive.")

# load the functions from utils file
from utils import *



### crear disco para la prueba de fidelidad


model_config = {
    "geometry": {
        "nx": 1536,
        "ny": 1536,
        "pixscale_au": 1.0,
        "inc_deg": 0.0,
        "pa_deg": 0.0,
        "x0_au": 0.0,
        "y0_au": 0.0,
    },

"axisymmetric_disk": {
        "central_component": {
            "enabled": True,
            "amp": 1.0,
            "sigma_au": 15.0,
        },
        "rings": [
            {
                "name": "ring1",
                "amp": 1,
                "r0_au": 50.0,
                "sigma_au": 4.0,
            },
            {
                "name": "ring2",
                "amp": 0.5,
                "r0_au": 200.0,
                "sigma_au": 35.0,
            },
            {
                "name": "ring3a",
                "amp": 1,
                "r0_au": 100.0,
                "sigma_au": 4.0,
            },
            {
                "name": "ring3b",
                "amp": 1,
                "r0_au": 117.0,
                "sigma_au": 4.0,
            },
        ],
      },
        "planets": [
        {
            "name": "planet1",
            "enabled": True,
            "amp_rel": 1.0,
            "amp_rel_to": "global_peak",
            "r_au": 70.0,
            "phi_deg": 135.0,
            "sigma_r_au": 5.0,
            "sigma_phi_au": 5.0,
            "theta_deg": 0.0,
        },
    ],
    }


# Construimos el modelo completo
model = build_intrinsic_emission_model(model_config)
coords = model["coords"]
# Extraemos mapas principales
img_axisym = model["img_axisym"]
img_planets_total = model["img_planets_total"]
img_asym_additive_total = model["img_asym_additive_total"]
img_asym_multiplicative_effect_total = model["img_asym_multiplicative_effect_total"]
img_total = model["img_total"]
# Graficamos disco axisimétrico
plot_image(img_axisym, coords, title="central_disk_plus_noresolved_rings_plus_planets",unit_label="Relative intensity",plane="sky",)
# Graficamos planetas
plot_image(img_planets_total,coords, title="Compact planets", unit_label="Relative intensity", plane="sky")

# Graficamos modelo total
plot_image(img_total, coords, title="Full_intrinsic_model",  unit_label="Relative intensity", plane="sky",)

#distance_pc = 140.0
#model_norm["coords"]["pixscale_au"]/distance_pc

# Normalizar imagen total
# Ejemplo: flujo total = 0.5 Jy
norm_result = normalize_model_image(img=model["img_total"], method="total_flux", value=1)

#Escalar todos los componentes del modelo
model_norm = apply_normalization_to_model_components( model, norm_result)

# Imagen total normalizada en Jy/pixel
img_jypix = model_norm["img_total_normalized"]

# Parametros observacionales
distance_pc = 140.0
pixscale_au = model_norm["coords"]["pixscale_au"]

bmaj_arcsec = 0.01
bmin_arcsec = 0.01
bpa_deg = 0.0

noise_std_jybeam = 5.0e-6   # 5 microJy/beam

## transform from Jy/pixel to Jy/arcsec2

image_jyarcsec2 = img_jypix / ((model_norm["coords"]["pixscale_au"]/distance_pc)**2)

# --------------------------------------------------------
# 6. Pipeline observacional
# --------------------------------------------------------
obs_result = convolve_convert_and_add_noise(
    img_jypix=img_jypix,    pixscale_au=pixscale_au,
    distance_pc=distance_pc,     bmaj_arcsec=bmaj_arcsec,
    bmin_arcsec=bmin_arcsec,    bpa_deg=bpa_deg,
    noise_std_jybeam=noise_std_jybeam,   random_seed=12345,
    return_kernel=True)

# Extraer productos
img_convolved_jypix = obs_result["img_convolved_jypix"]
img_convolved_jybeam = obs_result["img_convolved_jybeam"]

img_noisy_jybeam = obs_result["img_noisy_jybeam"]
noise_map_jybeam = obs_result["noise_map_jybeam"]

print("Factor Jy/pixel -> Jy/beam:", obs_result["conversion_factor"])
print("Omega_pix [arcsec^2]:", obs_result["omega_pix_arcsec2"])
print("Omega_beam [arcsec^2]:", obs_result["omega_beam_arcsec2"])

"""# ESTA BIEN PARA LA PRUEBA DE FIDELIDAD CON EL MPOL FOR DUMMYS?"""

comparar_graficos(img_convolved_jypix, img_convolved_jybeam, titulo1="Jy/pixel", titulo2="Jy/beam")

# save the data
from astropy.io import fits

# save image Jy/pix
hdul = fits.PrimaryHDU(img_jypix)
hdul.writeto('img_jypix.fits', overwrite=True)

# save image in Jy/arcsec2
hdul = fits.PrimaryHDU(image_jyarcsec2)
hdul.writeto('img_jyarcsec.fits', overwrite=True)

hdul = fits.PrimaryHDU(img_convolved_jypix)
hdul.writeto('img_convolved_jypix.fits', overwrite=True)

hdul = fits.PrimaryHDU(img_convolved_jybeam)
hdul.writeto('img_convolved_jybeam.fits', overwrite=True)

datos = [img_convolved_jypix, img_convolved_jybeam]
nombres = ["img_convolved_jypix", "img_convolved_jybeam"]
label_barra = ["Intensidad en Jy/pixel", "Intensidad en Jy/beam"]
# La función detectará que necesita 2 filas (3 en la primera, 2 en la segunda)
graficar_grid_imshow(datos, titulos=nombres, label_barra=label_barra, max_cols=2)

datos = [img_convolved_jybeam,img_noisy_jybeam,noise_map_jybeam]
nombres = ["img_convolved_jybeam", "img_noisy_jybeam","noise_map_jybeam"]
label_barra = ["Intensidad en Jy/pixel", "Intensidad en Jy/beam", "Intensidad en Jy/beam"]
graficar_grid_imshow(datos, titulos=nombres, max_cols=3, label_barra=label_barra)
hdul = fits.PrimaryHDU(img_noisy_jybeam)
hdul.writeto('img_convolved_jybeam_noisy.fits', overwrite=True)


