# -*- coding: utf-8 -*-
"""emission_pp_model_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C4tXF0l4trUrCKAiGzxO8VTrqDb7VKVI
"""

# MODELO
# DISCO CENTRAL + ANILLOS + PLANETAS + ASIMETRÍAS AZIMUTALES

import numpy as np
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive/')

import os

# Ajusta la ruta si tu carpeta está dentro de otras carpetas
# Por ejemplo: '/content/drive/MyDrive/proyectos/emision'
ruta_carpeta = '/content/drive/MyDrive/emission_disk'
os.chdir(ruta_carpeta)
print(os.getcwd())
import sys
sys.path.append('/content/drive/MyDrive/my_folder')
from ppdisk_components import *

### crear disco para la prueba de fidelidad


model_config_uniform_disk_15au = {
    "geometry": {
        "nx": 500,
        "ny": 500,
        "pixscale_au": 0.1,
        "inc_deg": 0.0,
        "pa_deg": 0.0,
        "x0_au": 0.0,
        "y0_au": 0.0,
    },

    "axisymmetric_disk": {
    "constant_disks": [
        {
            "enabled": True,
            "name": "uniform_disk_r15au",
            "amp": 1.0,
            "r_in_au": 0.0,
            "r_out_au": 5.0,

            # Usa 0.0 para un borde abrupto.
            # Usa 0.05--0.10 au si quieres evitar un borde infinitamente sharp.
            "edge_smoothing_au": 1,
        }
    ],
  "rings": [
      {"enabled": True,
      "name": "bright_inner_ring",
      "amp": 1.0,
      "r0_au": 2.0,
      "sigma_au": 0.5,
  },
      {"enabled": True,
      "name": "ring1",
      "amp": 1.0,
      "r0_au": 7.0,
      "sigma_au": 0.5,
  },
      {"enabled": True,
      "name": "ring2",
      "amp": 1.0,
      "r0_au": 8.5,  #three ngVLA beams
      "sigma_au": 0.5,
  }
  ],
  },

  "planets": [
    {
        "enabled": True,
        "name": "planet_1_inner",
        "amp_rel": 0.6,
        "amp_rel_to": "local_disk",
        "r_au": 3.5,
        "phi_deg": 45.0,
        "sigma_r_au": 0.15,
        "sigma_phi_au": 0.15,
        "theta_deg": 0.0,
    },
    {
        "enabled": True,
        "name": "planet_2_inner_rings",
        "amp_rel": 0.8,
        "amp_rel_to": "local_disk",
        "r_au": 7.8,
        "phi_deg": 210.0,
        "sigma_r_au": 0.15,
        "sigma_phi_au": 0.15,
        "theta_deg": 0.0,
    },
],
  "ring_asymmetries": [],
}

model = build_intrinsic_emission_model(model_config_uniform_disk_15au)

img_intrinsic = model["img_total"]
coords = model["coords"]

plot_image(
  img_intrinsic,
  coords,
  title="uniform_disk_15au_intrinsic",
  unit_label="relative intensity",
  plane="sky"
)

# Construimos el modelo completo
#model = build_intrinsic_emission_model(model_config_uniform_disk_15au)
#coords = model["coords"]
# Extraemos mapas principales
#img_axisym = model["img_axisym"]
#img_planets_total = model["img_planets_total"]
#img_asym_additive_total = model["img_asym_additive_total"]
#img_asym_multiplicative_effect_total = model["img_asym_multiplicative_effect_total"]
#img_total = model["img_total"]
# Graficamos disco axisimétrico
#plot_image(img_axisym, coords, title="central_disk_plus_noresolved_rings_plus_planets",unit_label="Relative intensity",plane="sky",)
# Graficamos planetas
#plot_image(img_planets_total,coords, title="Compact planets", unit_label="Relative intensity", plane="sky")

# Graficamos modelo total
#plot_image(img_total, coords, title="Full_intrinsic_model",  unit_label="Relative intensity", plane="sky",)

img_jypix = img_intrinsic.shape # image in Jy/pix

#### vamos  a usar un SN de 100 * noise para normalizar el flujo
# imagen modelo en Jy/pix
img_jypix = img_intrinsic # arbitrary units
# convolution to make the put the map in Jy/beam
# Parametros observacionales:
distance_pc = 140.0
pixscale_au = model_norm["coords"]["pixscale_au"]

bmaj_arcsec = 0.0036
bmin_arcsec = 0.0036
bpa_deg = 0.0
img_convolved_jypix = convolve_model_with_beam(
    img_jypix=img_jypix,    pixscale_au=pixscale_au,
    distance_pc=distance_pc,     bmaj_arcsec=bmaj_arcsec,
    bmin_arcsec=bmin_arcsec,    bpa_deg=bpa_deg,
    return_kernel=False)
img_convolved_jypix = img_convolved_jypix['img_convolved_jypix']

# image in Jy/beam
img_convolved_jybeam = convert_jypixel_to_jybeam(
    img_jypix=img_convolved_jypix,
    pixscale_au=pixscale_au,
    distance_pc=distance_pc,
    bmaj_arcsec=bmaj_arcsec,
    bmin_arcsec=bmin_arcsec,
)
img_noiseless_jybeam  = img_convolved_jybeam['img_jybeam']

rms_noise_jybeam = 1.8e-6 #from ngVLA exposure calculator tool
# Normalizar para que peak/rms = 100
snr_norm = normalize_to_peak_snr(
    img=img_noiseless_jybeam,
    rms_noise=rms_noise_jybeam,
    target_snr=100.0
)

img_noiseless_jybeam_scaled = snr_norm["img_normalized"]

# Agregar ruido gaussiano
img_noisy_jybeam = img_noiseless_jybeam_scaled + np.random.normal(
    0.0,
    rms_noise_jybeam,
    img_noiseless_jybeam_scaled.shape
)







# normalizacion a un flujo total

# Normalizar imagen total
norm_result = normalize_model_image(img=model["img_total"], method="total_flux", value=1)

#Escalar todos los componentes del modelo
model_norm = apply_normalization_to_model_components( model, norm_result)

# Imagen total normalizada en Jy/pixel
img_jypix = model_norm["img_total_normalized"]

# Parametros observacionales
distance_pc = 140.0
pixscale_au = model_norm["coords"]["pixscale_au"]

bmaj_arcsec = 0.0036
bmin_arcsec = 0.0036
bpa_deg = 0.0

noise_std_jybeam = 1.85e-6   # 5 microJy/beam

## transform from Jy/pixel to Jy/arcsec2

image_jyarcsec2 = img_jypix / ((model_norm["coords"]["pixscale_au"]/distance_pc)**2)

# --------------------------------------------------------
# 6. Pipeline observacional
# --------------------------------------------------------
obs_result = convolve_convert_and_add_noise(
    img_jypix=img_jypix,    pixscale_au=pixscale_au,
    distance_pc=distance_pc,     bmaj_arcsec=bmaj_arcsec,
    bmin_arcsec=bmin_arcsec,    bpa_deg=bpa_deg,
    noise_std_jybeam=noise_std_jybeam,   random_seed=12345,
    return_kernel=True)

# Extraer productos
img_convolved_jypix = obs_result["img_convolved_jypix"]
img_convolved_jybeam = obs_result["img_convolved_jybeam"]

img_noisy_jybeam = obs_result["img_noisy_jybeam"]
noise_map_jybeam = obs_result["noise_map_jybeam"]

print("Factor Jy/pixel -> Jy/beam:", obs_result["conversion_factor"])
print("Omega_pix [arcsec^2]:", obs_result["omega_pix_arcsec2"])
print("Omega_beam [arcsec^2]:", obs_result["omega_beam_arcsec2"])

"""# ESTA BIEN PARA LA PRUEBA DE FIDELIDAD CON EL MPOL FOR DUMMYS?"""

comparar_graficos(img_convolved_jypix, img_convolved_jybeam, titulo1="Jy/pixel", titulo2="Jy/beam")

# save the data
from astropy.io import fits

# save image Jy/pix
hdul = fits.PrimaryHDU(img_jypix)
hdul.writeto('img_jypix.fits', overwrite=True)

# save image in Jy/arcsec2
hdul = fits.PrimaryHDU(image_jyarcsec2)
hdul.writeto('img_jyarcsec.fits', overwrite=True)

hdul = fits.PrimaryHDU(img_convolved_jypix)
hdul.writeto('img_convolved_jypix.fits', overwrite=True)

hdul = fits.PrimaryHDU(img_convolved_jybeam)
hdul.writeto('img_convolved_jybeam.fits', overwrite=True)

import matplotlib.pyplot as plt
import numpy as np
import math


def graficar_grid_imshow(lista_imagenes, titulos=None, label_barra="Intensidad", max_cols=3, cmap='viridis'):
    """
    Grafica N imágenes en cuadrícula.
    'label_barra' puede ser un solo string (para todas) o una lista de strings (uno para cada imagen).
    """
    n = len(lista_imagenes)
    cols = min(n, max_cols)
    rows = math.ceil(n / cols)

    fig, ejes = plt.subplots(rows, cols, figsize=(5.8 * cols, 4.5 * rows))

    if n > 1:
        ejes_planos = ejes.flatten()
    else:
        ejes_planos = [ejes]

    for i in range(len(ejes_planos)):
        if i < n:
            im = ejes_planos[i].imshow(lista_imagenes[i], cmap=cmap)

            # --- Lógica inteligente para el label de la barra ---
            if isinstance(label_barra, list) and i < len(label_barra):
                label_actual = label_barra[i]
            elif isinstance(label_barra, list): # Por si la lista de labels es más corta que las imágenes
                label_actual = ""
            else:
                label_actual = label_barra # Si es un solo string, se usa el mismo para todas

            # Crear colorbar y asignar su label
            cbar = fig.colorbar(im, ax=ejes_planos[i], fraction=0.046, pad=0.04)
            cbar.set_label(label_actual, rotation=90, labelpad=15)

            if titulos and i < len(titulos):
                ejes_planos[i].set_title(titulos[i], pad=10)
            ejes_planos[i].axis('off')
        else:
            ejes_planos[i].axis('off')

    plt.tight_layout()
    plt.show()


datos = [img_convolved_jypix, img_convolved_jybeam]
nombres = ["img_convolved_jypix", "img_convolved_jybeam"]
label_barra = ["Intensidad en Jy/pixel", "Intensidad en Jy/beam"]
# La función detectará que necesita 2 filas (3 en la primera, 2 en la segunda)
graficar_grid_imshow(datos, titulos=nombres, label_barra=label_barra, max_cols=2)

datos = [img_convolved_jybeam,img_noisy_jybeam,noise_map_jybeam]
nombres = ["img_convolved_jybeam", "img_noisy_jybeam","noise_map_jybeam"]
label_barra = ["Intensidad en Jy/pixel", "Intensidad en Jy/beam", "Intensidad en Jy/beam"]
graficar_grid_imshow(datos, titulos=nombres, max_cols=3, label_barra=label_barra)
hdul = fits.PrimaryHDU(img_noisy_jybeam)
hdul.writeto('img_convolved_jybeam_noisy.fits', overwrite=True)

# create the true image



# modelo antiguo de la primera prueba de fidelidad

######## crear disco para la prueba de fidelidad
if __name__ == "__main__":

    model_config = {
        "geometry": {
            "nx": 1536,
            "ny": 1536,
            "pixscale_au": 1.0,
            "inc_deg": 0.0,
            "pa_deg": 0.0,
            "x0_au": 0.0,
            "y0_au": 0.0,
        },

    "axisymmetric_disk": {
            "central_component": {
                "enabled": True,
                "amp": 1.0,
                "sigma_au": 10.0,
            },
            "rings": [
                {
                    "name": "ring1",
                    "amp": 1,
                    "r0_au": 50.0,
                    "sigma_au": 4.0,
                },
                {
                    "name": "ring2",
                    "amp": 0.7,
                    "r0_au": 190.0,
                    "sigma_au": 25.0,
                },
                {
                    "name": "ring3a",
                    "amp": 1,
                    "r0_au": 100.0,
                    "sigma_au": 4.0,
                },
                {
                    "name": "ring3b",
                    "amp": 1,
                    "r0_au": 114.0,
                    "sigma_au": 4.0,
                },
            ],
          },
            "planets": [
            {
                "name": "planet1",
                "enabled": True,
                "amp_rel": 0.8,
                "amp_rel_to": "global_peak",
                "r_au": 65.0,
                "phi_deg": 110.0,
                "sigma_r_au": 3.0,
                "sigma_phi_au": 3.0,
                "theta_deg": 0.0,
            },
              {
                "name": "planet2a",
                "enabled": True,
                "amp_rel": 1,
                "amp_rel_to": "global_peak",
                "r_au": 65.0,
                "phi_deg": 250.0,
                "sigma_r_au": 3,
                "sigma_phi_au": 3,
                "theta_deg": 0.0,
            },
            {
                "name": "planet2b",
                "enabled": True,
                "amp_rel": 1,
                "amp_rel_to": "global_peak",
                "r_au": 65.0,
                "phi_deg": 260.0,
                "sigma_r_au": 3,
                "sigma_phi_au": 3,
                "theta_deg": 0.0,
            }
        ],
        }


    # Construimos el modelo completo
    model = build_intrinsic_emission_model(model_config)
    coords = model["coords"]
    # Extraemos mapas principales
    img_axisym = model["img_axisym"]
    img_planets_total = model["img_planets_total"]
    img_asym_additive_total = model["img_asym_additive_total"]
    img_asym_multiplicative_effect_total = model["img_asym_multiplicative_effect_total"]
    img_total = model["img_total"]
    # Graficamos disco axisimétrico
    plot_image(img_axisym, coords, title="central_disk_plus_noresolved_rings_plus_planets",unit_label="Relative intensity",plane="sky",)
    # Graficamos planetas
    plot_image(img_planets_total,coords, title="Compact planets", unit_label="Relative intensity", plane="sky")

    # Graficamos modelo total
    plot_image(img_total, coords, title="Full_intrinsic_model",  unit_label="Relative intensity", plane="sky",)



#### modelo de prueba de fidelidad y orientacion
### crear disco para la prueba de fidelidad
if __name__ == "__main__":

    model_config = {
        "geometry": {
            "nx": 1536,
            "ny": 1536,
            "pixscale_au": 1.0,
            "inc_deg": 0.0,
            "pa_deg": 0.0,
            "x0_au": 0.0,
            "y0_au": 0.0,
        },

    "axisymmetric_disk": {
            "central_component": {
                "enabled": True,
                "amp": 1.0,
                "sigma_au": 15.0,
            },
            "rings": [
                {
                    "name": "ring1",
                    "amp": 1,
                    "r0_au": 50.0,
                    "sigma_au": 4.0,
                },
                {
                    "name": "ring2",
                    "amp": 0.5,
                    "r0_au": 200.0,
                    "sigma_au": 35.0,
                },
                {
                    "name": "ring3a",
                    "amp": 1,
                    "r0_au": 100.0,
                    "sigma_au": 4.0,
                },
                {
                    "name": "ring3b",
                    "amp": 1,
                    "r0_au": 117.0,
                    "sigma_au": 4.0,
                },
            ],
          },
            "planets": [
            {
                "name": "planet1",
                "enabled": True,
                "amp_rel": 1.0,
                "amp_rel_to": "global_peak",
                "r_au": 70.0,
                "phi_deg": 135.0,
                "sigma_r_au": 5.0,
                "sigma_phi_au": 5.0,
                "theta_deg": 0.0,
            },
        ],
        }


    # Construimos el modelo completo
    model = build_intrinsic_emission_model(model_config)
    coords = model["coords"]
    # Extraemos mapas principales
    img_axisym = model["img_axisym"]
    img_planets_total = model["img_planets_total"]
    img_asym_additive_total = model["img_asym_additive_total"]
    img_asym_multiplicative_effect_total = model["img_asym_multiplicative_effect_total"]
    img_total = model["img_total"]
    # Graficamos disco axisimétrico
    plot_image(img_axisym, coords, title="central_disk_plus_noresolved_rings_plus_planets",unit_label="Relative intensity",plane="sky",)
    # Graficamos planetas
    plot_image(img_planets_total,coords, title="Compact planets", unit_label="Relative intensity", plane="sky")

    # Graficamos modelo total
    plot_image(img_total, coords, title="Full_intrinsic_model",  unit_label="Relative intensity", plane="sky",)